services:
  - type: web
    name: Muji-Report-Label-system
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      npm install -g docx
      mkdir -p node_modules
      ln -sf $(npm root -g)/docx node_modules/docx
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
